### ISSUE TITLE
Deleted half of my connections after install

### ISSUE THREAD

**Issue by slugo100** [scristalli/SQL-Developer-4-keepalive#19]
Have half as many connections I as did before install.   Not happy.

**Comment by scristalli** [comment]
Sorry to hear that, but your problem has hardly anything to do with the extension's code.
Similiar issues have been reported, such as this one listed in the [wiki](https://github.com/scristalli/SQL-Developer-4-keepalive/wiki/English-guide):

> WARNING | Some user have experienced a problem after installing the extension: they lost edits (renamings and groups) they had made to their connections. This might happen to you also.

Since this does not happen to everyone, it's likely to depend on some particular condition in your environment/your particular SQL Developer version in my opinion.

**Comment by slugo100** [comment]
Why would the install overwrite my current connections.xml with what appears to be an older version from a previous install?  Not good.  Not my fault.  Bad.  I have the most current version installed  4.1.3.20.  Why is the install altering the connections.xml file at all anyway - leave it alone.

**Comment by scristalli** [comment]
The beaty of open source is that you can verify by yourself that nothing in the extension refers to connections.xml
The installation passes through SQL Developer's OSGi framework, and simply registers the classes with the appropriate hooks.
There are two possible cases here:

1.  There is a major bug in the extension, which causes your problem
2.  Something else is causing it, and it's not related to the extension's code

Since out of thousands of downloads your problem seems to be rather isolated, pardon me if I believe I have reasons to point towards option #2.
I don't believe that it's going to be easy to figure out what your problem is, but feel free to provide more detail about your environment, and how to reproduce the problem if you want to make this report constructive. Thank you.

**Comment by derwin12** [comment]
Same here for me .. lost my connections. I guess this isnt for me anyways as I wanted it to keep my hive connection open and selecting from dual wont help me.

**Comment by lbischof84** [comment]
I can confirm this also as a bug, but I am quite sure this has nothing to do with this plugin.

Some of my connections also got lost after installing this plugin and restarting sql developer. The thing was, that on some db connections the login credentials have also been reverted to old values (e.g. our internal test server has been moved to a new machine).

After some research i have found a configuration from an old SQL developer installation in %APPDATA%\SQL Developer (Windows, for other platforms it is different). For some reason, the new SQL Developer has taken the connections.xml from the old installation and replaced the new connections.xml)

So, good news, it is not the plugins (probably), bad news, your connections are gone (maybe a file recovery tool will help you), and lesson learned: Make backups of app configurations, I have started with this the day I have installed this plugin.

**Comment by dlenski** [comment]
>I can confirm this also as a bug, but I am quite sure this has nothing to do with this plugin.
>
>Some of my connections also got lost after installing this plugin and restarting sql developer.

Happened to me too… rrggh. The only thing I'd suggest is to **make the warning about this issue more prominent** [on the wiki page](https://github.com/scristalli/SQL-Developer-4-keepalive/wiki/English-guide).

**Comment by dlenski** [comment]
I think I know what's going on here.

1. SQL Developer thinks that it is updating itself… not just installing an extension
2. SQL Developer looks for a config directory for an older version of itself:
    ```sh
    $ ls -ld ~/.sqldeveloper/system*
    drwxrwxr-x 122 dlenski dlenski 12288 Dec 11  2015 /home/dlenski/.sqldeveloper/system4.1.2.20.64
    drwxrwxr-x 126 dlenski dlenski 12288 Apr  6 12:35 /home/dlenski/.sqldeveloper/system4.1.3.20.78
    ```
3. SQL Developer blindly copies the `connections.xml` from the previous version into the directory for the latest one, even though _you're not actually installing a new version of the SQL Developer core_.

Yes… that is pretty stupid behavior. But it is not the stupidest thing I've ever seen SQL Developer do.  :angry:  :angry: :angry:. And it is definitely *not* the fault of this extension.

Though maybe there is a safer procedure to install the extension without triggering this (mis)behavior…?
